

name: ci-adapter-node
env:
  PATH: './packages/adapter-node'
on:
  push:
    branches: [main]
    paths:
      - 'packages/adapter-node/**'
  pull_request:
    branches: ['*']
    paths:
      - 'packages/adapter-node/**'

jobs:
  ci:
    name: Build and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Pull Branch
        uses: actions/checkout@v4

      - name: Install Bun
        uses: oven-sh/setup-bun@v2

      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - name: Build Package
        run: bun --filter ${{ env.PATH }} build

      - name: Build Types
        run: bun --filter ${{ env.PATH }} build:types

      - name: Lint Package
        run: bun --filter ${{ env.PATH }} lint
