name: ci-adapter-bun
on:
  push:
    branches: [main]
    paths:
      - "packages/adapter-bun-hono/**"
  pull_request:
    branches: ["*"]
    paths:
      - "packages/adapter-bun-hono/**"

env:
  PACKAGE_NAME: adapter-bun-hono

jobs:
  ci:
    name: Build and Lint adapter-bun-hono
    runs-on: ubuntu-latest
    steps:
      - name: Pull Branch
        uses: actions/checkout@v4

      - name: Install Bun
        uses: oven-sh/setup-bun@v2

      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - name: Build ${{ env.PACKAGE_NAME }} Package
        run: bun --filter ./packages/${{ env.PACKAGE_NAME }} build

      - name: Build ${{ env.PACKAGE_NAME }} Types
        run: bun --filter ./packages/${{ env.PACKAGE_NAME }} build:types

      - name: Lint ${{ env.PACKAGE_NAME }} Package
        run: bun --filter ./packages/${{ env.PACKAGE_NAME }} lint
