name: ci-adapter-node
on:
  push:
    branches: [main]
    paths:
      - 'packages/adapter-node/**'
  pull_request:
    branches: ['*']
    paths:
      - 'packages/adapter-node/**'

jobs:
  ci:
    name: build-and-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: "latest"

      - run: bun install --frozen-lockfile
      - run: bun --filter packages/adapter-node build
      - run: bun --filter packages/adapter-node lint
      - run: bun --filter packages/adapter-node format


    
    
    

